package org.mtr.mapping.holder;import org.mtr.mapping.annotation.MappedMethod;import org.mtr.mapping.tool.HolderBase;import javax.annotation.Nonnull;import javax.annotation.Nullable;import javax.annotation.ParametersAreNonnullByDefault;@ParametersAreNonnullByDefault@SuppressWarnings({"deprecation","unchecked","unused"})public final class ItemUsageContext  extends HolderBase<net.minecraft.world.item.context.UseOnContext>{public ItemUsageContext(net.minecraft.world.item.context.UseOnContext data){super(data);}@MappedMethod public static ItemUsageContext cast(HolderBase<?> data){return new ItemUsageContext((net.minecraft.world.item.context.UseOnContext)data.data);}@MappedMethod public static boolean isInstance(@Nullable HolderBase<?> data){return data!=null&&data.data instanceof net.minecraft.world.item.context.UseOnContext;}@MappedMethod public boolean equals(@Nullable Object data){return data instanceof HolderBase<?>&&this.data.equals(((HolderBase<?>)data).data);}@MappedMethod public boolean isInside(){return this.data.isInside();}@Nonnull@MappedMethod public Direction getHorizontalDirection(){return Direction.convert(this.data.getHorizontalDirection());}@Nonnull@MappedMethod public ItemStack getItemInHand(){return new ItemStack(this.data.getItemInHand());}@Nonnull@MappedMethod public BlockPos getClickedPos(){return new BlockPos(this.data.getClickedPos());}@Nonnull@MappedMethod public net.minecraft.world.phys.Vec3 getClickLocation(){return this.data.getClickLocation();}@Nonnull@MappedMethod public World getLevel(){return new World(this.data.getLevel());}@Nonnull@MappedMethod public Direction getClickedFace(){return Direction.convert(this.data.getClickedFace());}@MappedMethod public boolean isSecondaryUseActive(){return this.data.isSecondaryUseActive();}@Nonnull@MappedMethod public PlayerEntity getPlayer(){return new PlayerEntity(this.data.getPlayer());}@MappedMethod public  ItemUsageContext(PlayerEntity player,Hand hand,BlockHitResult hitResult){super(new net.minecraft.world.item.context.UseOnContext(player.data,hand.data,hitResult.data));}@MappedMethod public  ItemUsageContext(World level,PlayerEntity player,Hand hand,ItemStack itemStack,BlockHitResult hitResult){super(new net.minecraft.world.item.context.UseOnContext(level.data,player.data,hand.data,itemStack.data,hitResult.data));}@MappedMethod public float getRotation(){return this.data.getRotation();}@Nonnull@MappedMethod public Hand getHand(){return Hand.convert(this.data.getHand());}

@Nonnull@MappedMethod public Direction getPlayerFacing(){return getHorizontalDirection();}
@Nonnull@MappedMethod public BlockPos getBlockPos(){return getClickedPos();}
@Nonnull@MappedMethod public World getWorld(){return getLevel();}

@Nonnull@MappedMethod public Direction getSide(){return getClickedFace();}


@Nonnull@MappedMethod public ItemStack getStack(){return getItemInHand();}
@Nonnull@MappedMethod public Vector3d getHitPos(){return new Vector3d(getClickLocation());}
@MappedMethod public float getPlayerYaw(){final PlayerEntity p=getPlayer();return p==null?0f:p.data.getYRot();}
}